---
title: "Political Science 406 Lab 7: Bounds and Synthetic Control"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    highlight: tango
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: May 17, 2024

[Submit your lab here.](https://canvas.northwestern.edu/courses/211656/assignments/1392659)

### Problem 1: In-Your-Face Television

Consider Mutz’s 2007 APSR article, “Effects of “in-your-face” television discourse on perceptions of a
legitimate opposition.” The data for several of the analyses is available on the course website as mutz.csv.
The treatment variable, treat is randomly assigned and reflects whether a research subject saw a civil or
uncivil debate between a Democrat and a Republican. Outcome variables include mfvcanth for the feeling
thermometer score for your own candidate; lfvcanth, for the feeling thermometer score for the other candidate;
own, for the perceived legitimacy of policy arguments for the participant’s own issue stance; and other, for
the perceived legitimacy of policy arguments for the opposite issue stance. 

Look only at the bivariate relationship between treat and lfvcanth. How strong would omitted variables
need to be in order to substantially affect the estimated relationship? Answer using both sensitivity analysis
and extreme bounds analysis. (For the extreme bounds analysis, you may choose to dichotomize variables as helpful. This is artificial and probably shouldn't be done in real research, but can be useful in exercises.)

### Problem 2: Trump and Immigration

Can we use a synthetic controls strategy to come up with a statistical test of the effect of Trump’s
election in 2016 on (legal and/or illegal) immigration to the U.S.? Provide a proposed research design complete with
necessary data and estimator, explain the required assumptions, and discuss the strengths and weaknesses
of your proposal. Then show your results if possible.