---
title: "Political Science 406 Lab 4: Instrumental Variables"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
  pdf_document: default
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: May 8, 2026

[Submit your lab here.](https://canvas.northwestern.edu/courses/251621/assignments/1730776)

### Problem 1: Rainfall, Economic Shocks, and Civil Conflict

We are going to replicate an instrumental variables analysis of civil conflict in Africa, using rainfall as
an instrument for economic growth. Consider skimming [the article](https://doi.org/10.1086/421174), by Edward Miguel, Shanker Satyanath, and Ernest Sergenti. Download [replication data, which comes with variable definitions](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27324).

Please replicate model 5 of table 4. Do you get the same coefficient estimates? How about standard
errors? If there is a difference, can you explain why?

How strong is the instrument? Are there any obvious difficulties with the estimate?

Assume that the instrument is unproblematic. What is the causal meaning of the estimate?

### Problem 2: Diagnostics

Weak instruments: Compute the first‑stage F‑statistic manually. Is it above 10?

LATE interpretation: Who are the compliers in this context? Explain in plain language.

### Problem 3: Sensitivity to Exclusion Restriction

Suppose the exclusion restriction is violated because rainfall affects conflict through channels other than growth (e.g., agricultural livelihoods directly affect grievances). Use sensemakr to assess how strong a direct effect of rainfall on conflict would need to be to render your IV estimate insignificant. (Hint: you'll need to run a reduced‑form regression.)

