---
title: "Political Science 406 Lab 5: Regression Discontinuity Designs"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
  pdf_document: default
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: May 15, 2026

[Submit your lab here.](https://canvas.northwestern.edu/courses/251621/assignments/1730778)

### Problem 1: Regression Discontinuity and Partisan Sheriffs

Our [original article](https://doi.org/10.1017/S0003055419000613) here is by Thompson. 

Use the [replication data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CFASH6).

Use rdrobust to estimate the partisan difference for sheriffs at the 50% vote threshold. Report the conventional, bias‑corrected, and robust estimates. Plot the RD graph using rdplot.

### Problem 2: Manipulation Test

Conduct a density test using rddensity. Is there evidence of sorting around the cutoff? Interpret the plot and p‑value.

### Problem 3: Placebo Cutoffs

Choose two placebo cutoffs (e.g., 0.4 and 0.6) and re‑run rdrobust. Do you find significant effects? What does this tell you about the validity of the design?

### Problem 4: Covariate Balance

Test whether a pre‑treatment covariate (e.g., past election margin) is smooth at the cutoff using rdrobust with that covariate as the outcome. Report the result. If you find imbalance, what does that imply?
