---
title: "Political Science 406 Lab 6: Difference-in-Differences"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
  pdf_document: default
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: May 22, 2026

[Submit your lab here.](https://canvas.northwestern.edu/courses/251621/assignments/1730779)

### Problem 1: Democracy and Education: Classic 2×2 DiD

In this analysis, I will ask you to use data from the Alvarez et al. data set on regimes and economic
performance worldwide. The data are available as aclppanel.csv, and you can also access [a codebook](http://www.u.arizona.edu/~mishler/PrzeworskiCodebook.PDF).

Using these data, try to determine whether dictatorship/democracy (REG) has a positive or negative
causal effect on average education levels (EDT). Structure the analysis as a difference-in-differences setup using a two‑way fixed effects model (feols from fixest). Describe your findings.
 
### Problem 2: Testing Parallel Trends

Create a plot of the mean education level over time for democracies and dictatorships. Run a pre‑treatment trend test by interacting time with treatment indicator using only pre‑regime-change data for countries that transition from dictatorship to democracy and countries that are continuously dicatorships. What do you conclude?

### Problem 3: Staggered Adoption and Modern Estimators
The cross-national data have a staggered treatment (countries change regimes at different times). Use the did package (Callaway & Sant'Anna) to estimate the group‑time average treatment effects. Aggregate to an overall ATT. Compare with the TWFE estimate. Use bacondecomp to diagnose any negative weights in the TWFE estimate.

### Problem 4: Interactive Fixed Effects (Optional)

If time permits, use fect to estimate the ATT with interactive fixed effects. Compare the results to the previous estimators.